[API-26305] Update set-output
department-of-veterans-affairs/lighthouse-github-actions pull request #106
Opened 2023-05-22 15:26 UTC by declan-downie

2023-05-26 16:50 UTC, nick-gray-bah approved these changes

2023-05-30 15:45 UTC, KaemonIsland approved these changes

2023-05-30 16:15 UTC, merged

2023-05-30 16:17 UTC, zaslow requested changes

2023-05-30 16:17 UTC, zaslow commented on README.md
> +    paths: ['**/docs/*', '**/mkdocs.yaml'] # Additionally, using '**/*.md' will check all '.md' files for changes including in /docs
Let's just change this guidance to `paths: ['**/*.md', '**/mkdocs.yaml']`

2023-05-30 16:17 UTC, zaslow commented on .github/actions/techdocs-webhook/action.yml
> +        echo "EOF" >> "$GITHUB_ENV"
```
echo ${{ toJson(inputs) }} > tmp.json
echo "INPUTS<<EOF" >> $GITHUB_ENV
cat  $(jq --arg v $(basename ${{ inputs.repository }}) '."repo-name"=$v' tmp.json) >> $GITHUB_ENV
echo "EOF" >> $GITHUB_ENV
```

2023-05-30 16:18 UTC, zaslow commented on README.md
> +    paths: ['**/docs/*', '**/mkdocs.yaml'] # Additionally, using '**/*.md' will check all '.md' files for changes including in /docs
Just saw this was merged, these changes are minor and can be addressed separately