Api 25869 lint techdocs
department-of-veterans-affairs/lighthouse-github-actions pull request #109
Opened 2023-06-20 17:16 UTC by declan-downie

- Added linter to validate-techdocs action

2023-06-21 15:08 UTC, zaslow requested changes

2023-06-21 15:56 UTC, zaslow commented on .github/actions/validate-techdocs/action.yml
> +        ignore_path: ${{ env.lint_ignore_path }}
Does the `${{ env. }}` syntax work when declaring env vars using the `env` key? I thought that only worked when exporting to `$GITHUB_ENV`

2023-06-22 15:42 UTC, declan-downie commented on .github/actions/validate-techdocs/action.yml
> +        ignore_path: ${{ env.lint_ignore_path }}
I believe they operate under the same context - had to declare it in bash anyways though because declaring a variable in the `env:` section doesn't recognize `inputs.etc`

2023-06-23 19:34 UTC, KaemonIsland approved these changes

2023-06-23 20:06 UTC, nick-gray-bah approved these changes

2023-06-23 20:14 UTC, esciuckas-bah approved these changes

2023-06-26 17:46 UTC, zaslow approved these changes

2023-06-26 17:54 UTC, merged