[API 22542] prevent broken markdown links
department-of-veterans-affairs/lighthouse-github-actions pull request #86
Opened 2023-01-20 18:05 UTC by declan-downie

Added markdown link checker for validating techdocs

2023-01-23 21:42 UTC, zaslow requested changes

2023-01-23 21:42 UTC, zaslow commented on .github/actions/validate-techdocs/action.yml
> +    - name: Use JQ
This should be something more descriptive, like `Set AuthZ header`

2023-01-23 21:42 UTC, zaslow commented on .github/actions/validate-techdocs/action.yml
> +        echo '${{ steps.set-token.outputs.value }}' > mlc_config.json
Why not just do this as a part of the previous step, i.e.
```
cmd: |
  jq --arg v \ 
  'token ${{ inputs.token }}' '.httpHeaders[] .headers.Authorization=$v' \
  -r mlc_config.json" > mlc_config.json
```

2023-01-23 21:42 UTC, zaslow commented on .github/actions/validate-techdocs/action.yml
> +        cat mlc_config.json
You probably want to avoid `cat`ing this out since you just interpolated a secret into the file

2023-01-23 21:42 UTC, zaslow commented on mlc_config.json
> +    },
You can probably combine these with something like
```
{
  "pattern": "(?<=department-of-veterans-affairs/)([\w-_.]+)(/)?$",
  "replacement": "$1/contents/"
}

2023-01-23 22:33 UTC, declan-downie commented on .github/actions/validate-techdocs/action.yml
> +        cat mlc_config.json
Ah I just had that for debug and forgot about it - although it's been nice with github actions automatically starring out that (and all) secrets that would show up

2023-01-23 22:40 UTC, declan-downie commented on .github/actions/validate-techdocs/action.yml
> +        echo '${{ steps.set-token.outputs.value }}' > mlc_config.json
That action isn't able to run normal bash commands - it's just able to run JQ so I had to have it output to the file separately

2023-01-25 18:37 UTC, zaslow requested changes

2023-01-25 18:37 UTC, zaslow commented on .github/actions/validate-techdocs/action.yml
> +    - name: Set AuthZ header
This name is wrong - it's not setting a header here, it's just checking out the repo. You can probably just remove this line

2023-01-25 18:37 UTC, zaslow commented on .github/actions/validate-techdocs/action.yml
> +      uses: actions/checkout@v3
Doesn't this need to check out whatever repo is triggering the action? Otherwise it will only scan this repo

2023-01-25 19:19 UTC, declan-downie commented on .github/actions/validate-techdocs/action.yml
> +      uses: actions/checkout@v3
The full build-publish-docs workflow already calls checkout in the previous step and passes it in - do I even need to checkout here? Or does actions not use the same checkout action when stepping into the action?

2023-01-25 20:20 UTC, zaslow commented on .github/actions/validate-techdocs/action.yml
> +      uses: actions/checkout@v3
@declan-downie I thought that was the case - you don't need the checkout here, an action uses the local directory for the context from which it's called

2023-01-26 17:19 UTC, zaslow approved these changes

2023-01-26 17:34 UTC, merged